ARG EUPS_TAG
FROM ghcr.io/lsst/scipipe:al9-$EUPS_TAG

RUN source /opt/lsst/software/stack/loadLSST.bash && conda install mypy scipy-stubs types-shapely types-tqdm prek pre-commit && conda clean -a -y

USER root

RUN dnf install -y emacs-nox nodejs which man && dnf clean all

RUN npm install -g @fission-ai/openspec@latest
RUN npm install -g opencode-ai

RUN groupadd -g 1001 sandbox && useradd -m -u 1001 -g sandbox -d /sandbox -s /bin/bash sandbox

USER sandbox
WORKDIR /sandbox

RUN git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1

COPY --chown=sandbox:sandbox ./dotfiles/* .

# Source LSST startup as main user to initialize some things; it will be
# sourced in .bash
RUN source /opt/lsst/software/stack/loadLSST.bash

ENV HISTFILE=/sandbox/.history/.bash_history

CMD ["/bin/bash", "-il"]
